### ISSUE TITLE
Opening a large text file freezes the app and uses up a large amount of CPU

### ISSUE THREAD

**Issue by GlitchMasta47** [fungus-soft/desktop#4]
I opened a 2.4mb text file and the app almost immediately froze and started using 45% of my CPU. This can be fixed by only loading a very small portion of the file at a time like the Windows Notepad does for large files.

**Comment by IsaiahPatton** [comment]
Try the latest commit that I just pushed. It should optimize the loading.
Got a 5mb text file to load in 0.3 seconds instead of the previous 14 seconds for me.

**Comment by GlitchMasta47** [comment]
Sorry for the super late reply, the jar file you linked seems to still freeze when opening the same text file.

**Comment by IsaiahPatton** [comment]
Try this one: [jar](https://ci.codemc.io/job/Fungus-Software/job/Desktop%20Environment/lastBuild/artifact/target/DesktopEnvirement-indev.jar)

**Comment by GlitchMasta47** [comment]
Seems to still be freezing but the CPU usage isn't getting as high as it was before. Also this time the notepad window shows up before it freezes, previously it didn't.

**Comment by IsaiahPatton** [comment]
could you send me a copy of the large text file?

**Comment by GlitchMasta47** [comment]
Just realized the issue, it's a JSON file with no whitespace and no newlines and the app loading the first line is the same as just loading the entire file.
